/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author meera saymeh
 */
import java.awt.Color;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.*;

public class JF extends javax.swing.JFrame {

    /**
     * Creates new form JF
     */
    JLabel pic;
    Timer tm;
    int x = 0;
    int slideWidth = 800;
    int slideHegiht = 500;
    int imageOffset = 100;
    int delay = 800;
    //Images Path In Array
    String[] list = {
        "file:/C:/Users/meera saymeh/Desktop/flash/-1450778869180-41d0601e046e.jpg",//0
        "file:/C:/Users/meera saymeh/Desktop/flash/dog-and-cat-1024x683.jpeg",//1
        "file:/C:/Users/meera saymeh/Desktop/flash/cat-eyeing-food.jpg",//2
        "file:/C:/Users/meera saymeh/Desktop/flash/dog-and-cat-cuddling-cropped.jpg",//3
        "file:/C:/Users/meera saymeh/Desktop/flash/download (1).jpg",//4
        "file:/C:/Users/meera saymeh/Desktop/flash/original.jpg",//5
    };

    public JF() {
        initComponents();

        pic = new JLabel();
        pic.setBounds(40, 30, slideWidth - imageOffset, slideHegiht - imageOffset);
        SetImageSize(list.length - 1);
        //set a timer
        tm = new Timer(delay, new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                SetImageSize(x);
                x += 1;
                if (x >= list.length) {
                    x = 0;
                }
            }
        });
        add(pic);
        tm.start();
        setLayout(null);
        setSize(slideWidth, slideHegiht);
        getContentPane().setBackground(Color.decode("#bdb67b"));
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setVisible(true);
    }

    public void SetImageSize(int i) {
        ImageIcon icon = new ImageIcon(list[i]);
        Image img = icon.getImage();
        Image newImg = img.getScaledInstance(pic.getWidth(), pic.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon newImc = new ImageIcon(newImg);
        pic.setIcon(newImc);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jButton6 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jButton6.setText("jButton6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton1.setBackground(new java.awt.Color(67, 122, 113));
        jButton1.setFont(new java.awt.Font("Belwe Cn BT", 2, 13)); // NOI18N
        jButton1.setText("Home");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(210, 10, 80, 30);

        jButton3.setBackground(new java.awt.Color(67, 122, 113));
        jButton3.setFont(new java.awt.Font("Belwe Cn BT", 2, 13)); // NOI18N
        jButton3.setText("Dog");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton3MouseEntered(evt);
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton3MouseExited(evt);
            }

            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton3MousePressed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(520, 10, 70, 30);

        jButton4.setBackground(new java.awt.Color(67, 122, 113));
        jButton4.setFont(new java.awt.Font("Belwe Cn BT", 2, 13)); // NOI18N
        jButton4.setForeground(new java.awt.Color(51, 51, 51));
        jButton4.setText("Shop");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(670, 10, 80, 30);

        jButton5.setBackground(new java.awt.Color(67, 122, 113));
        jButton5.setFont(new java.awt.Font("Belwe Cn BT", 2, 13)); // NOI18N
        jButton5.setText("Contact Us");
        getContentPane().add(jButton5);
        jButton5.setBounds(820, 10, 90, 30);

        jPanel1.setBackground(new java.awt.Color(247, 177, 212));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel1MouseExited(evt);
            }
        });
        jPanel1.setLayout(null);

        jButton10.setBackground(new java.awt.Color(247, 177, 212));
        jButton10.setFont(new java.awt.Font("Belwe Cn BT", 2, 14)); // NOI18N
        jButton10.setText("Food");
        jPanel1.add(jButton10);
        jButton10.setBounds(0, 0, 120, 30);

        jButton11.setBackground(new java.awt.Color(247, 177, 212));
        jButton11.setFont(new java.awt.Font("Belwe Cn BT", 2, 14)); // NOI18N
        jButton11.setText("Toys");
        jPanel1.add(jButton11);
        jButton11.setBounds(0, 30, 120, 30);

        jButton12.setBackground(new java.awt.Color(247, 177, 212));
        jButton12.setFont(new java.awt.Font("Belwe Cn BT", 2, 14)); // NOI18N
        jButton12.setText("Bath care");
        jPanel1.add(jButton12);
        jButton12.setBounds(0, 60, 120, 30);

        jButton13.setBackground(new java.awt.Color(247, 177, 212));
        jButton13.setFont(new java.awt.Font("Belwe Cn BT", 2, 14)); // NOI18N
        jButton13.setText("Adoption");
        jPanel1.add(jButton13);
        jButton13.setBounds(0, 90, 120, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(520, 40, 120, 0);

        jButton2.setBackground(new java.awt.Color(67, 122, 113));
        jButton2.setFont(new java.awt.Font("Belwe Cn BT", 2, 13)); // NOI18N
        jButton2.setText("Cat");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton2MouseEntered(evt);
            }

            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton2MousePressed(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(360, 10, 70, 30);

        jPanel2.setBackground(new java.awt.Color(247, 177, 212));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel2MouseExited(evt);
            }
        });
        jPanel2.setLayout(null);

        jButton7.setBackground(new java.awt.Color(247, 177, 212));
        jButton7.setFont(new java.awt.Font("Belwe Cn BT", 2, 14)); // NOI18N
        jButton7.setText("Food");
        jPanel2.add(jButton7);
        jButton7.setBounds(0, 0, 120, 30);

        jButton8.setBackground(new java.awt.Color(247, 177, 212));
        jButton8.setFont(new java.awt.Font("Belwe Cn BT", 2, 14)); // NOI18N
        jButton8.setText("Toys");
        jPanel2.add(jButton8);
        jButton8.setBounds(0, 30, 120, 27);

        jButton9.setBackground(new java.awt.Color(247, 177, 212));
        jButton9.setFont(new java.awt.Font("Belwe Cn BT", 2, 14)); // NOI18N
        jButton9.setText("Bath care");
        jPanel2.add(jButton9);
        jButton9.setBounds(0, 55, 120, 30);

        jButton14.setBackground(new java.awt.Color(247, 177, 212));
        jButton14.setFont(new java.awt.Font("Belwe Cn BT", 2, 14)); // NOI18N
        jButton14.setText("Adoption");
        jPanel2.add(jButton14);
        jButton14.setBounds(0, 85, 120, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(360, 39, 120, 100);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\meera saymeh\\Desktop\\Edl0Iom.jpeg")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1000, 50);

        pack();
    }// </editor-fold>                        

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jButton3MouseEntered(java.awt.event.MouseEvent evt) {
        jPanel1.setSize(120, 120);

    }

    private void jButton3MouseExited(java.awt.event.MouseEvent evt) {

    }

    private void jPanel1MouseExited(java.awt.event.MouseEvent evt) {
        jPanel1.setSize(0, 0);
    }

    private void jButton3MousePressed(java.awt.event.MouseEvent evt) {
        jPanel1.setSize(0, 0);
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jButton2MouseEntered(java.awt.event.MouseEvent evt) {
        jPanel2.setSize(120, 115);
    }

    private void jButton2MousePressed(java.awt.event.MouseEvent evt) {
        jPanel2.setSize(0, 0);
    }

    private void jPanel2MouseExited(java.awt.event.MouseEvent evt) {
        jPanel2.setSize(0, 0);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JF().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration                   
}
